// generiert von scripts/ratgeber-index.mjs — nicht von Hand ändern
import type { Ratgeberseite } from '../ratgeber-seiten'
import s0 from './anbau-kosten.json'
import s1 from './badsanierung-kosten.json'
import s2 from './barrierefreies-bad.json'
import s3 from './boden-verlegen-kosten.json'
import s4 from './bodenplatte-kosten.json'
import s5 from './carport-kosten.json'
import s6 from './dachdaemmung-kosten.json'
import s7 from './dachfenster-einbauen-kosten.json'
import s8 from './dachgaube-kosten.json'
import s9 from './dachsanierung-kosten.json'
import s10 from './elektrik-erneuern-kosten.json'
import s11 from './energetische-sanierung.json'
import s12 from './fassade-streichen-kosten.json'
import s13 from './fassadendaemmung-kosten.json'
import s14 from './fenster-austauschen-kosten.json'
import s15 from './fliesenleger-kosten.json'
import s16 from './fussbodenheizung-nachruesten-kosten.json'
import s17 from './haus-bauen-kosten.json'
import s18 from './hausanschluss-kosten.json'
import s19 from './haustuer-kosten.json'
import s20 from './kernsanierung-kosten.json'
import s21 from './photovoltaik-kosten.json'
import s22 from './terrassenueberdachung-kosten.json'
import s23 from './treppe-kosten.json'
import s24 from './waermepumpe-kosten.json'
import s25 from './wallbox-kosten.json'
import s26 from './wintergarten-kosten.json'
import s27 from './zaun-kosten.json'

export const RATGEBERSEITEN = ([s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21, s22, s23, s24, s25, s26, s27] as Ratgeberseite[]).sort((a, b) => a.rang - b.rang)
